import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import authRouter from "./auth";
import userRouter from "./user";
import ordersRouter from "./orders";
import adminRouter from "./admin";
import servicesRouter from "./services";
import cryptoRouter from "./crypto";
import passkeyRouter from "./passkey";
import checksRouter from "./checks";
import checkProvidersRouter from "./checkProviders";
const router: IRouter = Router();
router.use(healthRouter);
router.use(productsRouter);
router.use("/auth", authRouter);
router.use("/user/passkey", passkeyRouter);
router.use("/user", userRouter);
router.use("/orders", ordersRouter);
router.use("/admin", adminRouter);
router.use("/services", servicesRouter);
router.use("/crypto", cryptoRouter);
router.use(checksRouter);
router.use("/admin", checkProvidersRouter);
export default router;
